### ISSUE TITLE
Spike - s3 on DO

### ISSUE THREAD

**Issue by jakobii** [hyqe/brigand#24]
- look into digitalocean spaces, and figure out how to used AWS s3 client with it. 
- understand authentication option with digitalocean spaces. 
- ensure the digitalocean space can only be accessed by our service, not public.

**Comment by LukeOchoa** [comment]
Digital Ocean is making a weird abstraction over only the gui side of AWS S3 as far as I can tell
You interact with (digital ocean spaces s3) programmatically the same way you would a normal AWS S3
Digital Ocean will provide you with the necessary credentials (which you can supply at runtime as Environment Variables)

Go to DigitialOcean.com -> Login -> API(on the left bottom side of the website) -> Click "Spaces Keys"
From here you can generate a new key or use the current ones they've given you

You NEED:
1) Access Key; This is always visible on the website. You can reaccess this whenever you need it.
2) Secret Key; This will disapear after some time or after you leave the page or something.
Its currently labeled just as "Secret"... Make sure to save it.

AWS lets you generate a crentials object at runtime. You just need to provide it access_key, secret_key
You need to provide credentials anytime you interact with the S3.
AWS S3 SDK apis will usually require four things: Bucket Name, Endpoint(url/uri), Access key & Secret key(for credentials) 

BUCKET_NAME:
The bucket_name is the name of the "Digital Ocean Spaces" Space -- i.e. brigand-storage

ENDPOINT:
In order to query the s3 you need to set the endpoint.
Go to DigitialOcean.com -> Login -> Spaces (leftside navbar) -> Click on storage name -> Origin-Endpoint (copypasta)
Remove the <your_storage_spaces_name>. from the URL(including the dot .), The AWS session object will reconfigure the endpoint
to have your bucket_name put back into the endpoint url. It will not work otherwise & you will have a dumb endpoint
